[package]
name = "rust_play"
version = "0.0.1"
authors = ["Charles Yang <donchoa@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.3.14"
rayon = "1.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench"
harness = false
